# Register user

POST http://localhost:3000/user/register HTTP/1.1
content-type: application/json

{
    "name": "Jahangir Ahmad",
    "email": "test2@email.com",
    "password": "123456"
}

### Login user

POST http://localhost:3000/user/login HTTP/1.1
content-type: application/json

{
    "email": "test2@email.com",
    "password": "123456"
}
